/* tslint:disable */
/* eslint-disable */
/**
 * Blood Bank API
 * Blood Bag Management System for Web-In-Cloud system
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: alexander8.matuska@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BloodBag
 */
export interface BloodBag {
    /**
     * Unique id of the blood bag
     * @type {string}
     * @memberof BloodBag
     */
    id: string;
    /**
     * Blood group of the bag
     * @type {string}
     * @memberof BloodBag
     */
    bloodGroup: BloodBagBloodGroupEnum;
    /**
     * Rh factor of the blood bag
     * @type {string}
     * @memberof BloodBag
     */
    rhFactor: BloodBagRhFactorEnum;
    /**
     * Date when the blood was collected
     * @type {Date}
     * @memberof BloodBag
     */
    collectionDate?: Date;
    /**
     * Volume of the blood bag in ml
     * @type {number}
     * @memberof BloodBag
     */
    volume: number;
    /**
     * Current status of the blood bag
     * @type {string}
     * @memberof BloodBag
     */
    status?: BloodBagStatusEnum;
    /**
     * Identifier of the blood donor
     * @type {string}
     * @memberof BloodBag
     */
    donorId?: string;
    /**
     * Additional notes about the blood bag
     * @type {string}
     * @memberof BloodBag
     */
    notes?: string;
    /**
     * Timestamp when the record was created
     * @type {Date}
     * @memberof BloodBag
     */
    createdAt?: Date;
}


/**
 * @export
 */
export const BloodBagBloodGroupEnum = {
    A: 'A',
    B: 'B',
    Ab: 'AB',
    O: 'O'
} as const;
export type BloodBagBloodGroupEnum = typeof BloodBagBloodGroupEnum[keyof typeof BloodBagBloodGroupEnum];

/**
 * @export
 */
export const BloodBagRhFactorEnum = {
    Positive: 'positive',
    Negative: 'negative'
} as const;
export type BloodBagRhFactorEnum = typeof BloodBagRhFactorEnum[keyof typeof BloodBagRhFactorEnum];

/**
 * @export
 */
export const BloodBagStatusEnum = {
    Available: 'available',
    Reserved: 'reserved',
    Issued: 'issued',
    Expired: 'expired',
    Destroyed: 'destroyed'
} as const;
export type BloodBagStatusEnum = typeof BloodBagStatusEnum[keyof typeof BloodBagStatusEnum];


/**
 * Check if a given object implements the BloodBag interface.
 */
export function instanceOfBloodBag(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "bloodGroup" in value;
    isInstance = isInstance && "rhFactor" in value;
    isInstance = isInstance && "volume" in value;

    return isInstance;
}

export function BloodBagFromJSON(json: any): BloodBag {
    return BloodBagFromJSONTyped(json, false);
}

export function BloodBagFromJSONTyped(json: any, ignoreDiscriminator: boolean): BloodBag {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'bloodGroup': json['bloodGroup'],
        'rhFactor': json['rhFactor'],
        'collectionDate': !exists(json, 'collectionDate') ? undefined : (new Date(json['collectionDate'])),
        'volume': json['volume'],
        'status': !exists(json, 'status') ? undefined : json['status'],
        'donorId': !exists(json, 'donorId') ? undefined : json['donorId'],
        'notes': !exists(json, 'notes') ? undefined : json['notes'],
        'createdAt': !exists(json, 'createdAt') ? undefined : (new Date(json['createdAt'])),
    };
}

export function BloodBagToJSON(value?: BloodBag | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'bloodGroup': value.bloodGroup,
        'rhFactor': value.rhFactor,
        'collectionDate': value.collectionDate === undefined ? undefined : (value.collectionDate.toISOString()),
        'volume': value.volume,
        'status': value.status,
        'donorId': value.donorId,
        'notes': value.notes,
        'createdAt': value.createdAt === undefined ? undefined : (value.createdAt.toISOString()),
    };
}

