/* tslint:disable */
/* eslint-disable */
/**
 * Blood Bank API
 * Blood Bag Management System for Web-In-Cloud system
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: alexander8.matuska@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  BloodBag,
} from '../models';
import {
    BloodBagFromJSON,
    BloodBagToJSON,
} from '../models';

export interface CreateBloodBagRequest {
    bloodBankId: string;
    bloodBag: BloodBag;
}

export interface DeleteBloodBagRequest {
    bloodBankId: string;
    bagId: string;
}

export interface GetBloodBagRequest {
    bloodBankId: string;
    bagId: string;
}

export interface GetBloodBagsRequest {
    bloodBankId: string;
    bloodGroup?: GetBloodBagsBloodGroupEnum;
    rhFactor?: GetBloodBagsRhFactorEnum;
    status?: GetBloodBagsStatusEnum;
}

export interface UpdateBloodBagRequest {
    bloodBankId: string;
    bagId: string;
    bloodBag: BloodBag;
}

/**
 * BloodBankBagsApi - interface
 * 
 * @export
 * @interface BloodBankBagsApiInterface
 */
export interface BloodBankBagsApiInterface {
    /**
     * Use this method to register a new blood bag into the blood bank.
     * @summary Creates new blood bag entry
     * @param {string} bloodBankId pass the id of the particular blood bank
     * @param {BloodBag} bloodBag Blood bag to register
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof BloodBankBagsApiInterface
     */
    createBloodBagRaw(requestParameters: CreateBloodBagRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BloodBag>>;

    /**
     * Use this method to register a new blood bag into the blood bank.
     * Creates new blood bag entry
     */
    createBloodBag(requestParameters: CreateBloodBagRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BloodBag>;

    /**
     * Use this method to delete the specific blood bag from the blood bank.
     * @summary Deletes specific blood bag
     * @param {string} bloodBankId pass the id of the particular blood bank
     * @param {string} bagId pass the id of the particular blood bag
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof BloodBankBagsApiInterface
     */
    deleteBloodBagRaw(requestParameters: DeleteBloodBagRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     * Use this method to delete the specific blood bag from the blood bank.
     * Deletes specific blood bag
     */
    deleteBloodBag(requestParameters: DeleteBloodBagRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * By using bloodBankId and bagId you can get details of a particular blood bag.
     * @summary Provides details about a blood bag
     * @param {string} bloodBankId pass the id of the particular blood bank
     * @param {string} bagId pass the id of the particular blood bag
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof BloodBankBagsApiInterface
     */
    getBloodBagRaw(requestParameters: GetBloodBagRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BloodBag>>;

    /**
     * By using bloodBankId and bagId you can get details of a particular blood bag.
     * Provides details about a blood bag
     */
    getBloodBag(requestParameters: GetBloodBagRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BloodBag>;

    /**
     * By using bloodBankId you get list of blood bags in the blood bank
     * @summary Provides list of blood bags in the bank
     * @param {string} bloodBankId pass the id of the particular blood bank
     * @param {'A' | 'B' | 'AB' | 'O'} [bloodGroup] filter by blood group
     * @param {'positive' | 'negative'} [rhFactor] filter by Rh factor
     * @param {'available' | 'reserved' | 'issued' | 'expired' | 'destroyed'} [status] filter by status
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof BloodBankBagsApiInterface
     */
    getBloodBagsRaw(requestParameters: GetBloodBagsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<BloodBag>>>;

    /**
     * By using bloodBankId you get list of blood bags in the blood bank
     * Provides list of blood bags in the bank
     */
    getBloodBags(requestParameters: GetBloodBagsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<BloodBag>>;

    /**
     * Use this method to update content of a blood bag entry.
     * @summary Updates specific blood bag
     * @param {string} bloodBankId pass the id of the particular blood bank
     * @param {string} bagId pass the id of the particular blood bag
     * @param {BloodBag} bloodBag Blood bag data to update
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof BloodBankBagsApiInterface
     */
    updateBloodBagRaw(requestParameters: UpdateBloodBagRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BloodBag>>;

    /**
     * Use this method to update content of a blood bag entry.
     * Updates specific blood bag
     */
    updateBloodBag(requestParameters: UpdateBloodBagRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BloodBag>;

}

/**
 * 
 */
export class BloodBankBagsApi extends runtime.BaseAPI implements BloodBankBagsApiInterface {

    /**
     * Use this method to register a new blood bag into the blood bank.
     * Creates new blood bag entry
     */
    async createBloodBagRaw(requestParameters: CreateBloodBagRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BloodBag>> {
        if (requestParameters.bloodBankId === null || requestParameters.bloodBankId === undefined) {
            throw new runtime.RequiredError('bloodBankId','Required parameter requestParameters.bloodBankId was null or undefined when calling createBloodBag.');
        }

        if (requestParameters.bloodBag === null || requestParameters.bloodBag === undefined) {
            throw new runtime.RequiredError('bloodBag','Required parameter requestParameters.bloodBag was null or undefined when calling createBloodBag.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/blood-bank/{bloodBankId}/bags`.replace(`{${"bloodBankId"}}`, encodeURIComponent(String(requestParameters.bloodBankId))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: BloodBagToJSON(requestParameters.bloodBag),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BloodBagFromJSON(jsonValue));
    }

    /**
     * Use this method to register a new blood bag into the blood bank.
     * Creates new blood bag entry
     */
    async createBloodBag(requestParameters: CreateBloodBagRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BloodBag> {
        const response = await this.createBloodBagRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Use this method to delete the specific blood bag from the blood bank.
     * Deletes specific blood bag
     */
    async deleteBloodBagRaw(requestParameters: DeleteBloodBagRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.bloodBankId === null || requestParameters.bloodBankId === undefined) {
            throw new runtime.RequiredError('bloodBankId','Required parameter requestParameters.bloodBankId was null or undefined when calling deleteBloodBag.');
        }

        if (requestParameters.bagId === null || requestParameters.bagId === undefined) {
            throw new runtime.RequiredError('bagId','Required parameter requestParameters.bagId was null or undefined when calling deleteBloodBag.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/blood-bank/{bloodBankId}/bags/{bagId}`.replace(`{${"bloodBankId"}}`, encodeURIComponent(String(requestParameters.bloodBankId))).replace(`{${"bagId"}}`, encodeURIComponent(String(requestParameters.bagId))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Use this method to delete the specific blood bag from the blood bank.
     * Deletes specific blood bag
     */
    async deleteBloodBag(requestParameters: DeleteBloodBagRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteBloodBagRaw(requestParameters, initOverrides);
    }

    /**
     * By using bloodBankId and bagId you can get details of a particular blood bag.
     * Provides details about a blood bag
     */
    async getBloodBagRaw(requestParameters: GetBloodBagRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BloodBag>> {
        if (requestParameters.bloodBankId === null || requestParameters.bloodBankId === undefined) {
            throw new runtime.RequiredError('bloodBankId','Required parameter requestParameters.bloodBankId was null or undefined when calling getBloodBag.');
        }

        if (requestParameters.bagId === null || requestParameters.bagId === undefined) {
            throw new runtime.RequiredError('bagId','Required parameter requestParameters.bagId was null or undefined when calling getBloodBag.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/blood-bank/{bloodBankId}/bags/{bagId}`.replace(`{${"bloodBankId"}}`, encodeURIComponent(String(requestParameters.bloodBankId))).replace(`{${"bagId"}}`, encodeURIComponent(String(requestParameters.bagId))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BloodBagFromJSON(jsonValue));
    }

    /**
     * By using bloodBankId and bagId you can get details of a particular blood bag.
     * Provides details about a blood bag
     */
    async getBloodBag(requestParameters: GetBloodBagRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BloodBag> {
        const response = await this.getBloodBagRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * By using bloodBankId you get list of blood bags in the blood bank
     * Provides list of blood bags in the bank
     */
    async getBloodBagsRaw(requestParameters: GetBloodBagsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<BloodBag>>> {
        if (requestParameters.bloodBankId === null || requestParameters.bloodBankId === undefined) {
            throw new runtime.RequiredError('bloodBankId','Required parameter requestParameters.bloodBankId was null or undefined when calling getBloodBags.');
        }

        const queryParameters: any = {};

        if (requestParameters.bloodGroup !== undefined) {
            queryParameters['bloodGroup'] = requestParameters.bloodGroup;
        }

        if (requestParameters.rhFactor !== undefined) {
            queryParameters['rhFactor'] = requestParameters.rhFactor;
        }

        if (requestParameters.status !== undefined) {
            queryParameters['status'] = requestParameters.status;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/blood-bank/{bloodBankId}/bags`.replace(`{${"bloodBankId"}}`, encodeURIComponent(String(requestParameters.bloodBankId))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(BloodBagFromJSON));
    }

    /**
     * By using bloodBankId you get list of blood bags in the blood bank
     * Provides list of blood bags in the bank
     */
    async getBloodBags(requestParameters: GetBloodBagsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<BloodBag>> {
        const response = await this.getBloodBagsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Use this method to update content of a blood bag entry.
     * Updates specific blood bag
     */
    async updateBloodBagRaw(requestParameters: UpdateBloodBagRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BloodBag>> {
        if (requestParameters.bloodBankId === null || requestParameters.bloodBankId === undefined) {
            throw new runtime.RequiredError('bloodBankId','Required parameter requestParameters.bloodBankId was null or undefined when calling updateBloodBag.');
        }

        if (requestParameters.bagId === null || requestParameters.bagId === undefined) {
            throw new runtime.RequiredError('bagId','Required parameter requestParameters.bagId was null or undefined when calling updateBloodBag.');
        }

        if (requestParameters.bloodBag === null || requestParameters.bloodBag === undefined) {
            throw new runtime.RequiredError('bloodBag','Required parameter requestParameters.bloodBag was null or undefined when calling updateBloodBag.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/blood-bank/{bloodBankId}/bags/{bagId}`.replace(`{${"bloodBankId"}}`, encodeURIComponent(String(requestParameters.bloodBankId))).replace(`{${"bagId"}}`, encodeURIComponent(String(requestParameters.bagId))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: BloodBagToJSON(requestParameters.bloodBag),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BloodBagFromJSON(jsonValue));
    }

    /**
     * Use this method to update content of a blood bag entry.
     * Updates specific blood bag
     */
    async updateBloodBag(requestParameters: UpdateBloodBagRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BloodBag> {
        const response = await this.updateBloodBagRaw(requestParameters, initOverrides);
        return await response.value();
    }

}

/**
 * @export
 */
export const GetBloodBagsBloodGroupEnum = {
    A: 'A',
    B: 'B',
    Ab: 'AB',
    O: 'O'
} as const;
export type GetBloodBagsBloodGroupEnum = typeof GetBloodBagsBloodGroupEnum[keyof typeof GetBloodBagsBloodGroupEnum];
/**
 * @export
 */
export const GetBloodBagsRhFactorEnum = {
    Positive: 'positive',
    Negative: 'negative'
} as const;
export type GetBloodBagsRhFactorEnum = typeof GetBloodBagsRhFactorEnum[keyof typeof GetBloodBagsRhFactorEnum];
/**
 * @export
 */
export const GetBloodBagsStatusEnum = {
    Available: 'available',
    Reserved: 'reserved',
    Issued: 'issued',
    Expired: 'expired',
    Destroyed: 'destroyed'
} as const;
export type GetBloodBagsStatusEnum = typeof GetBloodBagsStatusEnum[keyof typeof GetBloodBagsStatusEnum];
