/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface Cv3amBloodBankApp {
        "apiBase": string;
        /**
          * @default ""
         */
        "basePath": string;
        "bloodBankId": string;
    }
    interface Cv3amBloodBankEditor {
        "apiBase": string;
        "bagId": string;
        "bloodBankId": string;
    }
    interface Cv3amBloodBankList {
        "apiBase": string;
        "bloodBankId": string;
    }
}
export interface Cv3amBloodBankEditorCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLCv3amBloodBankEditorElement;
}
export interface Cv3amBloodBankListCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLCv3amBloodBankListElement;
}
declare global {
    interface HTMLCv3amBloodBankAppElement extends Components.Cv3amBloodBankApp, HTMLStencilElement {
    }
    var HTMLCv3amBloodBankAppElement: {
        prototype: HTMLCv3amBloodBankAppElement;
        new (): HTMLCv3amBloodBankAppElement;
    };
    interface HTMLCv3amBloodBankEditorElementEventMap {
        "editor-closed": string;
    }
    interface HTMLCv3amBloodBankEditorElement extends Components.Cv3amBloodBankEditor, HTMLStencilElement {
        addEventListener<K extends keyof HTMLCv3amBloodBankEditorElementEventMap>(type: K, listener: (this: HTMLCv3amBloodBankEditorElement, ev: Cv3amBloodBankEditorCustomEvent<HTMLCv3amBloodBankEditorElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLCv3amBloodBankEditorElementEventMap>(type: K, listener: (this: HTMLCv3amBloodBankEditorElement, ev: Cv3amBloodBankEditorCustomEvent<HTMLCv3amBloodBankEditorElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLCv3amBloodBankEditorElement: {
        prototype: HTMLCv3amBloodBankEditorElement;
        new (): HTMLCv3amBloodBankEditorElement;
    };
    interface HTMLCv3amBloodBankListElementEventMap {
        "bag-clicked": string;
    }
    interface HTMLCv3amBloodBankListElement extends Components.Cv3amBloodBankList, HTMLStencilElement {
        addEventListener<K extends keyof HTMLCv3amBloodBankListElementEventMap>(type: K, listener: (this: HTMLCv3amBloodBankListElement, ev: Cv3amBloodBankListCustomEvent<HTMLCv3amBloodBankListElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLCv3amBloodBankListElementEventMap>(type: K, listener: (this: HTMLCv3amBloodBankListElement, ev: Cv3amBloodBankListCustomEvent<HTMLCv3amBloodBankListElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLCv3amBloodBankListElement: {
        prototype: HTMLCv3amBloodBankListElement;
        new (): HTMLCv3amBloodBankListElement;
    };
    interface HTMLElementTagNameMap {
        "cv3am-blood-bank-app": HTMLCv3amBloodBankAppElement;
        "cv3am-blood-bank-editor": HTMLCv3amBloodBankEditorElement;
        "cv3am-blood-bank-list": HTMLCv3amBloodBankListElement;
    }
}
declare namespace LocalJSX {
    interface Cv3amBloodBankApp {
        "apiBase"?: string;
        /**
          * @default ""
         */
        "basePath"?: string;
        "bloodBankId"?: string;
    }
    interface Cv3amBloodBankEditor {
        "apiBase"?: string;
        "bagId"?: string;
        "bloodBankId"?: string;
        "onEditor-closed"?: (event: Cv3amBloodBankEditorCustomEvent<string>) => void;
    }
    interface Cv3amBloodBankList {
        "apiBase"?: string;
        "bloodBankId"?: string;
        "onBag-clicked"?: (event: Cv3amBloodBankListCustomEvent<string>) => void;
    }

    interface Cv3amBloodBankAppAttributes {
        "basePath": string;
        "apiBase": string;
        "bloodBankId": string;
    }
    interface Cv3amBloodBankEditorAttributes {
        "bagId": string;
        "bloodBankId": string;
        "apiBase": string;
    }
    interface Cv3amBloodBankListAttributes {
        "apiBase": string;
        "bloodBankId": string;
    }

    interface IntrinsicElements {
        "cv3am-blood-bank-app": Omit<Cv3amBloodBankApp, keyof Cv3amBloodBankAppAttributes> & { [K in keyof Cv3amBloodBankApp & keyof Cv3amBloodBankAppAttributes]?: Cv3amBloodBankApp[K] } & { [K in keyof Cv3amBloodBankApp & keyof Cv3amBloodBankAppAttributes as `attr:${K}`]?: Cv3amBloodBankAppAttributes[K] } & { [K in keyof Cv3amBloodBankApp & keyof Cv3amBloodBankAppAttributes as `prop:${K}`]?: Cv3amBloodBankApp[K] };
        "cv3am-blood-bank-editor": Omit<Cv3amBloodBankEditor, keyof Cv3amBloodBankEditorAttributes> & { [K in keyof Cv3amBloodBankEditor & keyof Cv3amBloodBankEditorAttributes]?: Cv3amBloodBankEditor[K] } & { [K in keyof Cv3amBloodBankEditor & keyof Cv3amBloodBankEditorAttributes as `attr:${K}`]?: Cv3amBloodBankEditorAttributes[K] } & { [K in keyof Cv3amBloodBankEditor & keyof Cv3amBloodBankEditorAttributes as `prop:${K}`]?: Cv3amBloodBankEditor[K] };
        "cv3am-blood-bank-list": Omit<Cv3amBloodBankList, keyof Cv3amBloodBankListAttributes> & { [K in keyof Cv3amBloodBankList & keyof Cv3amBloodBankListAttributes]?: Cv3amBloodBankList[K] } & { [K in keyof Cv3amBloodBankList & keyof Cv3amBloodBankListAttributes as `attr:${K}`]?: Cv3amBloodBankListAttributes[K] } & { [K in keyof Cv3amBloodBankList & keyof Cv3amBloodBankListAttributes as `prop:${K}`]?: Cv3amBloodBankList[K] };
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "cv3am-blood-bank-app": LocalJSX.IntrinsicElements["cv3am-blood-bank-app"] & JSXBase.HTMLAttributes<HTMLCv3amBloodBankAppElement>;
            "cv3am-blood-bank-editor": LocalJSX.IntrinsicElements["cv3am-blood-bank-editor"] & JSXBase.HTMLAttributes<HTMLCv3amBloodBankEditorElement>;
            "cv3am-blood-bank-list": LocalJSX.IntrinsicElements["cv3am-blood-bank-list"] & JSXBase.HTMLAttributes<HTMLCv3amBloodBankListElement>;
        }
    }
}
