/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface Cv3amAmbulanceWlList {
    }
}
declare global {
    interface HTMLCv3amAmbulanceWlListElement extends Components.Cv3amAmbulanceWlList, HTMLStencilElement {
    }
    var HTMLCv3amAmbulanceWlListElement: {
        prototype: HTMLCv3amAmbulanceWlListElement;
        new (): HTMLCv3amAmbulanceWlListElement;
    };
    interface HTMLElementTagNameMap {
        "cv3am-ambulance-wl-list": HTMLCv3amAmbulanceWlListElement;
    }
}
declare namespace LocalJSX {
    interface Cv3amAmbulanceWlList {
    }
    interface IntrinsicElements {
        "cv3am-ambulance-wl-list": Cv3amAmbulanceWlList;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "cv3am-ambulance-wl-list": LocalJSX.IntrinsicElements["cv3am-ambulance-wl-list"] & JSXBase.HTMLAttributes<HTMLCv3amAmbulanceWlListElement>;
        }
    }
}
