/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface Cv1amAmbulanceWlList {
    }
}
declare global {
    interface HTMLCv1amAmbulanceWlListElement extends Components.Cv1amAmbulanceWlList, HTMLStencilElement {
    }
    var HTMLCv1amAmbulanceWlListElement: {
        prototype: HTMLCv1amAmbulanceWlListElement;
        new (): HTMLCv1amAmbulanceWlListElement;
    };
    interface HTMLElementTagNameMap {
        "cv1am-ambulance-wl-list": HTMLCv1amAmbulanceWlListElement;
    }
}
declare namespace LocalJSX {
    interface Cv1amAmbulanceWlList {
    }
    interface IntrinsicElements {
        "cv1am-ambulance-wl-list": Cv1amAmbulanceWlList;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "cv1am-ambulance-wl-list": LocalJSX.Cv1amAmbulanceWlList & JSXBase.HTMLAttributes<HTMLCv1amAmbulanceWlListElement>;
        }
    }
}
